### ISSUE TITLE
New Titles search...error in Description

### ISSUE THREAD

**Issue by dheian** [MythTV-Themes/TintedGlass#6]
When you go to Manage Recordings->Search Lists->New Titles, the description says "Pick a program to record FOR a list of new titles". Should be "Pick a program to record FROM a list of new titles", :-)

**Comment by hpeters** [comment]
My theme just shows the default description that MythTV supplies it.
So this is actually a MythTV bug.

Relevant TintedGlass code in menu-ui.xml starting line number 174.
<textarea name="description" from="basetextarea">
    <area>20,1,-20,-1</area>
    <minsize shrink="short" vanish="true">5,5</minsize>
    <font>basesmalldarkyellow</font>
    <align>allcenter</align>
    <multiline>no</multiline>
</textarea>

**Comment by dheian** [comment]
I'll post this to the Myth list then. Thanks.
